stages:
  - format
  - lint
  - test

format-erlang:
  stage: format
  image: erlang:latest
  script:
    - rebar3 get-deps
    - rebar3 format
  only:
    - merge_requests
    - master

linter-erlang:
  stage: lint
  image: erlang:latest
  script:
    - rebar3 get-deps
    - rebar3 lint
  only:
    - merge_requests
    - master

test-erlang:
  stage: test
  image: erlang:latest
  script:
    - rebar3 get-deps
    - rebar3 eunit
  only:
    - merge_requests
    - master