name: Check Erlang

on:
  push:
    branches:
      - main


jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: erlang:latest

    steps:
      - run: rebar3 get-deps
      - run: rebar3 lint

  unit:
    runs-on: ubuntu-latest
    container:
      image: erlang:latest

    steps:
      - run: rebar3 get-deps
      - run: rebar3 eunit